module.exports = {
  DECIMAL_PRECISION: 4,
  MAX_TRANSACTION_AMOUNT: 999999999.9999,
  MIN_TRANSACTION_AMOUNT: 0.0001,
  DEFAULT_PAGINATION_LIMIT: 10,
  MAX_PAGINATION_LIMIT: 100,
  TRANSACTION_TYPES: {
    CREDIT: 'CREDIT',
    DEBIT: 'DEBIT'
  },
  API_RESPONSES: {
    SUCCESS: 'success',
    ERROR: 'error',
    VALIDATION_ERROR: 'validation_error'
  }
};